### ISSUE TITLE
`deno_ast` Might Simplify TypeScript Compilation

### ISSUE THREAD

**Issue by zicklag** [jakobhellermann/bevy_mod_js_scripting#1]
The `deno_ast` crate might simplify the TypeScript transpiler code a little.

https://github.com/denoland/deno/blob/2703996dea73c496d79fcedf165886a1659622d1/core/examples/ts_module_loader.rs#L68-L78

Unless you need to customize the process. I couldn't tell yet if you were doing anything that needed more control over the process that `deno_ast` provides.

**Comment by jakobhellermann** [comment]
Done in https://github.com/jakobhellermann/bevy_mod_js_scripting/commit/ae334f5dcd2f1629484c55f178d17fd596376263
