### ISSUE TITLE
Should We Capitalize the World Global?

### ISSUE THREAD

**Issue by zicklag** [jakobhellermann/bevy_mod_js_scripting#30]
As I started extending the scripting API with custom ops for my game, I started to like the pattern of creating capitalized globals such as `Assets` or `MapElement` to act as namespaces for different categories of operations.

I like the capitalization because it makes it more intuitive that the type is a global namespace or class and not a local variable.

This is really just a style preference, but I was curious what you thought.

**Comment by jakobhellermann** [comment]
My first reacting is that I prefer `world`. The `Value` object really fields like a namespace with a collection of functions, but `world` feels just like a global variable `let world: World;`.

**Comment by zicklag** [comment]
Yeah, that makes enough sense to me. 👍
